const typeTranslate = {
  Planet: "Планета",
  "Space station": "Космическая станция",
  Microverse: "Микроверс",
  Cluster: "Кластер",
  Dimension: "Измерение",
  TV: "Телевидение",
  Resort: "Курорт",
  Dream: "Сон",
  "Fantasy town": "Фэнтезийный город",
  Memory: "Воспоминание",
  Consciousness: "Сознание",
  "Death Star": "Звезда Смерти",
  Asteroid: "Астероид",
  "Acid Plant": "Кислотный завод",
  Reality: "Реальность",
  Spacecraft: "Космический корабль",
  Base: "База",
  Liquid: "Жидкость",
  "Elemental Rings": "Элементальные кольца",
  Human: "Человек",
  Space: "Космос",
  Hell: "Ад",
  Country: "Страна",
  "Police Department": "Полицейский участок",
  Menagerie: "Менажерия",
  unknown: "неизвестно",
  Game: "Игра",
  Customs: "Таможня",
  Box: "Коробка",
  "Dwarf planet (Celestial Dwarf)": "Карликовая планета",
  Daycare: "Детский сад",
  Miniverse: "Минивселенная",
  Teenyverse: "Крошечная вселенная",
  Spa: "Спа",
  Arcade: "Аркада",
  Machine: "Машина",
  "Artificially generated world": "Искусственно созданный мир",
  Diegesis: "Диегезис",
  Quadrant: "Квадрант",
  Quasar: "Квазар",
  Mount: "Гора",
  Convention: "Конвенция",
  Woods: "Леса",
  "Non-Diegetic Alternative Reality":
    "Недиегетическая альтернативная реальность",
  Nightmare: "Кошмар",
};

const dimensionTranslate = {
  unknown: "неизвестно",
};

export { typeTranslate, dimensionTranslate };
